import type { OfficialCurriculumGuide } from '@math-app/shared';

export const grade4Kntt2026Curriculum: OfficialCurriculumGuide = {
  grade: 4,
  schoolYear: '2026-2027',
  framework: 'Chương trình giáo dục phổ thông 2018',
  officialTextbookSeries: 'Kết nối tri thức với cuộc sống',
  policyDecision: '3588/QĐ-BGDĐT (26/12/2025)',
  referenceSeries: ['Cánh Diều', 'Chân trời sáng tạo'],
  chapters: [
    {
      id: 'kntt-chapter-01',
      order: 1,
      title: 'Ôn tập và bổ sung',
      semester: 1,
      lessonNumbers: [1, 2, 3, 4, 5, 6],
    },
    {
      id: 'kntt-chapter-02',
      order: 2,
      title: 'Góc và đơn vị đo góc',
      semester: 1,
      lessonNumbers: [7, 8, 9],
    },
    {
      id: 'kntt-chapter-03',
      order: 3,
      title: 'Số có nhiều chữ số',
      semester: 1,
      lessonNumbers: [10, 11, 12, 13, 14, 15, 16],
    },
    {
      id: 'kntt-chapter-04',
      order: 4,
      title: 'Một số đơn vị đo đại lượng',
      semester: 1,
      lessonNumbers: [17, 18, 19, 20, 21],
    },
    {
      id: 'kntt-chapter-05',
      order: 5,
      title: 'Phép cộng và phép trừ',
      semester: 1,
      lessonNumbers: [22, 23, 24, 25, 26],
    },
    {
      id: 'kntt-chapter-06',
      order: 6,
      title: 'Đường thẳng vuông góc. Đường thẳng song song',
      semester: 1,
      lessonNumbers: [27, 28, 29, 30, 31, 32],
    },
    {
      id: 'kntt-chapter-07',
      order: 7,
      title: 'Ôn tập học kì 1',
      semester: 1,
      lessonNumbers: [33, 34, 35, 36, 37],
    },
    {
      id: 'kntt-chapter-08',
      order: 8,
      title: 'Phép nhân và phép chia',
      semester: 2,
      lessonNumbers: [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48],
    },
    {
      id: 'kntt-chapter-09',
      order: 9,
      title: 'Làm quen với yếu tố thống kê, xác suất',
      semester: 2,
      lessonNumbers: [49, 50, 51, 52],
    },
    {
      id: 'kntt-chapter-10',
      order: 10,
      title: 'Phân số',
      semester: 2,
      lessonNumbers: [53, 54, 55, 56, 57, 58, 59],
    },
    {
      id: 'kntt-chapter-11',
      order: 11,
      title: 'Phép cộng, phép trừ phân số',
      semester: 2,
      lessonNumbers: [60, 61, 62],
    },
    {
      id: 'kntt-chapter-12',
      order: 12,
      title: 'Phép nhân, phép chia phân số',
      semester: 2,
      lessonNumbers: [63, 64, 65, 66],
    },
    {
      id: 'kntt-chapter-13',
      order: 13,
      title: 'Ôn tập cuối năm',
      semester: 2,
      lessonNumbers: [67, 68, 69, 70, 71, 72, 73],
    },
  ],
  lessons: [
    {
      number: 1,
      id: 'kntt-lesson-01',
      chapterId: 'kntt-chapter-01',
      title: 'Ôn tập các số đến 100 000',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'read-write-numbers',
        'write-natural-numbers',
        'digit-place-value',
        'compare-numbers',
      ],
    },
    {
      number: 2,
      id: 'kntt-lesson-02',
      chapterId: 'kntt-chapter-01',
      title: 'Ôn tập các phép tính trong phạm vi 100 000',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'column-addition',
        'column-subtraction',
        'multiply-one-digit',
        'divide-one-digit',
        'operation-order',
      ],
    },
    {
      number: 3,
      id: 'kntt-lesson-03',
      chapterId: 'kntt-chapter-01',
      title: 'Số chẵn, số lẻ',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['even-odd-numbers'],
    },
    {
      number: 4,
      id: 'kntt-lesson-04',
      chapterId: 'kntt-chapter-01',
      title: 'Biểu thức chứa chữ',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['variable-expression'],
    },
    {
      number: 5,
      id: 'kntt-lesson-05',
      chapterId: 'kntt-chapter-01',
      title: 'Giải bài toán có ba bước tính',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['three-step-word-problem'],
    },
    {
      number: 6,
      id: 'kntt-lesson-06',
      chapterId: 'kntt-chapter-01',
      title: 'Luyện tập chung',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'read-write-numbers',
        'operation-order',
        'even-odd-numbers',
        'variable-expression',
        'three-step-word-problem',
      ],
    },
    {
      number: 7,
      id: 'kntt-lesson-07',
      chapterId: 'kntt-chapter-02',
      title: 'Đo góc, đơn vị đo góc',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['measure-angle-degrees'],
    },
    {
      number: 8,
      id: 'kntt-lesson-08',
      chapterId: 'kntt-chapter-02',
      title: 'Góc nhọn, góc tù, góc bẹt',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['classify-angles'],
    },
    {
      number: 9,
      id: 'kntt-lesson-09',
      chapterId: 'kntt-chapter-02',
      title: 'Luyện tập chung',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: ['measure-angle-degrees', 'classify-angles'],
    },
    {
      number: 10,
      id: 'kntt-lesson-10',
      chapterId: 'kntt-chapter-03',
      title: 'Số có sáu chữ số. Số 1 000 000',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['numbers-to-million', 'read-write-numbers'],
    },
    {
      number: 11,
      id: 'kntt-lesson-11',
      chapterId: 'kntt-chapter-03',
      title: 'Hàng và lớp',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['place-and-class', 'digit-place-value'],
    },
    {
      number: 12,
      id: 'kntt-lesson-12',
      chapterId: 'kntt-chapter-03',
      title: 'Các số trong phạm vi lớp triệu',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['numbers-to-million', 'read-write-numbers', 'write-natural-numbers'],
    },
    {
      number: 13,
      id: 'kntt-lesson-13',
      chapterId: 'kntt-chapter-03',
      title: 'Làm tròn số đến hàng trăm nghìn',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['round-numbers'],
    },
    {
      number: 14,
      id: 'kntt-lesson-14',
      chapterId: 'kntt-chapter-03',
      title: 'So sánh các số có nhiều chữ số',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['compare-numbers', 'order-natural-numbers'],
    },
    {
      number: 15,
      id: 'kntt-lesson-15',
      chapterId: 'kntt-chapter-03',
      title: 'Làm quen với dãy số tự nhiên',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['natural-number-sequence'],
    },
    {
      number: 16,
      id: 'kntt-lesson-16',
      chapterId: 'kntt-chapter-03',
      title: 'Luyện tập chung',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'numbers-to-million',
        'place-and-class',
        'round-numbers',
        'compare-numbers',
        'natural-number-sequence',
      ],
    },
    {
      number: 17,
      id: 'kntt-lesson-17',
      chapterId: 'kntt-chapter-04',
      title: 'Yến, tạ, tấn',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['mass-conversion'],
    },
    {
      number: 18,
      id: 'kntt-lesson-18',
      chapterId: 'kntt-chapter-04',
      title: 'Đề-xi-mét vuông, mét vuông, mi-li-mét vuông',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['area-conversion'],
    },
    {
      number: 19,
      id: 'kntt-lesson-19',
      chapterId: 'kntt-chapter-04',
      title: 'Giây, thế kỉ',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['time-conversion'],
    },
    {
      number: 20,
      id: 'kntt-lesson-20',
      chapterId: 'kntt-chapter-04',
      title: 'Thực hành và trải nghiệm sử dụng một số đơn vị đo đại lượng',
      semester: 1,
      kind: 'EXPERIENCE',
      problemTypeIds: [
        'mass-conversion',
        'area-conversion',
        'time-conversion',
        'compare-measurements',
      ],
    },
    {
      number: 21,
      id: 'kntt-lesson-21',
      chapterId: 'kntt-chapter-04',
      title: 'Luyện tập chung',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'mass-conversion',
        'area-conversion',
        'time-conversion',
        'compare-measurements',
      ],
    },
    {
      number: 22,
      id: 'kntt-lesson-22',
      chapterId: 'kntt-chapter-05',
      title: 'Phép cộng các số có nhiều chữ số',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['column-addition'],
    },
    {
      number: 23,
      id: 'kntt-lesson-23',
      chapterId: 'kntt-chapter-05',
      title: 'Phép trừ các số có nhiều chữ số',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['column-subtraction'],
    },
    {
      number: 24,
      id: 'kntt-lesson-24',
      chapterId: 'kntt-chapter-05',
      title: 'Tính chất giao hoán và kết hợp của phép cộng',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['addition-properties'],
    },
    {
      number: 25,
      id: 'kntt-lesson-25',
      chapterId: 'kntt-chapter-05',
      title: 'Tìm hai số biết tổng và hiệu của hai số đó',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['sum-difference-problem'],
    },
    {
      number: 26,
      id: 'kntt-lesson-26',
      chapterId: 'kntt-chapter-05',
      title: 'Luyện tập chung',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'column-addition',
        'column-subtraction',
        'addition-properties',
        'sum-difference-problem',
      ],
    },
    {
      number: 27,
      id: 'kntt-lesson-27',
      chapterId: 'kntt-chapter-06',
      title: 'Hai đường thẳng vuông góc',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['perpendicular-lines'],
    },
    {
      number: 28,
      id: 'kntt-lesson-28',
      chapterId: 'kntt-chapter-06',
      title: 'Thực hành và trải nghiệm vẽ hai đường thẳng vuông góc',
      semester: 1,
      kind: 'EXPERIENCE',
      problemTypeIds: ['perpendicular-lines'],
    },
    {
      number: 29,
      id: 'kntt-lesson-29',
      chapterId: 'kntt-chapter-06',
      title: 'Hai đường thẳng song song',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['parallel-perpendicular'],
    },
    {
      number: 30,
      id: 'kntt-lesson-30',
      chapterId: 'kntt-chapter-06',
      title: 'Thực hành và trải nghiệm vẽ hai đường thẳng song song',
      semester: 1,
      kind: 'EXPERIENCE',
      problemTypeIds: ['parallel-perpendicular'],
    },
    {
      number: 31,
      id: 'kntt-lesson-31',
      chapterId: 'kntt-chapter-06',
      title: 'Hình bình hành, hình thoi',
      semester: 1,
      kind: 'CORE',
      problemTypeIds: ['recognize-parallelogram-rhombus'],
    },
    {
      number: 32,
      id: 'kntt-lesson-32',
      chapterId: 'kntt-chapter-06',
      title: 'Luyện tập chung',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'perpendicular-lines',
        'parallel-perpendicular',
        'recognize-parallelogram-rhombus',
      ],
    },
    {
      number: 33,
      id: 'kntt-lesson-33',
      chapterId: 'kntt-chapter-07',
      title: 'Ôn tập các số đến lớp triệu',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'numbers-to-million',
        'place-and-class',
        'round-numbers',
        'compare-numbers',
        'natural-number-sequence',
      ],
    },
    {
      number: 34,
      id: 'kntt-lesson-34',
      chapterId: 'kntt-chapter-07',
      title: 'Ôn tập phép cộng, phép trừ',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: ['column-addition', 'column-subtraction', 'addition-properties'],
    },
    {
      number: 35,
      id: 'kntt-lesson-35',
      chapterId: 'kntt-chapter-07',
      title: 'Ôn tập hình học',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'measure-angle-degrees',
        'classify-angles',
        'perpendicular-lines',
        'parallel-perpendicular',
        'recognize-parallelogram-rhombus',
      ],
    },
    {
      number: 36,
      id: 'kntt-lesson-36',
      chapterId: 'kntt-chapter-07',
      title: 'Ôn tập đo lường',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: ['mass-conversion', 'area-conversion', 'time-conversion'],
    },
    {
      number: 37,
      id: 'kntt-lesson-37',
      chapterId: 'kntt-chapter-07',
      title: 'Ôn tập chung',
      semester: 1,
      kind: 'REVIEW',
      problemTypeIds: [
        'numbers-to-million',
        'column-addition',
        'column-subtraction',
        'measure-angle-degrees',
        'mass-conversion',
      ],
    },
    {
      number: 38,
      id: 'kntt-lesson-38',
      chapterId: 'kntt-chapter-08',
      title: 'Nhân với số có một chữ số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['multiply-one-digit'],
    },
    {
      number: 39,
      id: 'kntt-lesson-39',
      chapterId: 'kntt-chapter-08',
      title: 'Chia cho số có một chữ số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['divide-one-digit', 'division-remainder'],
    },
    {
      number: 40,
      id: 'kntt-lesson-40',
      chapterId: 'kntt-chapter-08',
      title: 'Tính chất giao hoán và kết hợp của phép nhân',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['multiplication-properties'],
    },
    {
      number: 41,
      id: 'kntt-lesson-41',
      chapterId: 'kntt-chapter-08',
      title: 'Nhân, chia với 10, 100, 1 000, ...',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['multiply-divide-powers-of-ten'],
    },
    {
      number: 42,
      id: 'kntt-lesson-42',
      chapterId: 'kntt-chapter-08',
      title: 'Tính chất phân phối của phép nhân đối với phép cộng',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['distributive-property'],
    },
    {
      number: 43,
      id: 'kntt-lesson-43',
      chapterId: 'kntt-chapter-08',
      title: 'Nhân với số có hai chữ số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['multiply-two-digits'],
    },
    {
      number: 44,
      id: 'kntt-lesson-44',
      chapterId: 'kntt-chapter-08',
      title: 'Chia cho số có hai chữ số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['divide-two-digits'],
    },
    {
      number: 45,
      id: 'kntt-lesson-45',
      chapterId: 'kntt-chapter-08',
      title: 'Thực hành và trải nghiệm ước lượng trong tính toán',
      semester: 2,
      kind: 'EXPERIENCE',
      problemTypeIds: ['estimate-calculation'],
    },
    {
      number: 46,
      id: 'kntt-lesson-46',
      chapterId: 'kntt-chapter-08',
      title: 'Tìm số trung bình cộng',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['average-problem'],
    },
    {
      number: 47,
      id: 'kntt-lesson-47',
      chapterId: 'kntt-chapter-08',
      title: 'Bài toán liên quan đến rút về đơn vị',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['unit-rate-problem'],
    },
    {
      number: 48,
      id: 'kntt-lesson-48',
      chapterId: 'kntt-chapter-08',
      title: 'Luyện tập chung',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'multiply-one-digit',
        'divide-one-digit',
        'multiplication-properties',
        'multiply-divide-powers-of-ten',
        'distributive-property',
        'multiply-two-digits',
        'divide-two-digits',
        'estimate-calculation',
        'average-problem',
        'unit-rate-problem',
      ],
    },
    {
      number: 49,
      id: 'kntt-lesson-49',
      chapterId: 'kntt-chapter-09',
      title: 'Dãy số liệu thống kê',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['statistical-data-series', 'read-data-table'],
    },
    {
      number: 50,
      id: 'kntt-lesson-50',
      chapterId: 'kntt-chapter-09',
      title: 'Biểu đồ cột',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['read-bar-chart', 'compare-chart-data'],
    },
    {
      number: 51,
      id: 'kntt-lesson-51',
      chapterId: 'kntt-chapter-09',
      title: 'Số lần xuất hiện của một sự kiện',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['event-frequency'],
    },
    {
      number: 52,
      id: 'kntt-lesson-52',
      chapterId: 'kntt-chapter-09',
      title: 'Luyện tập chung',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'statistical-data-series',
        'read-data-table',
        'read-bar-chart',
        'compare-chart-data',
        'event-frequency',
      ],
    },
    {
      number: 53,
      id: 'kntt-lesson-53',
      chapterId: 'kntt-chapter-10',
      title: 'Khái niệm phân số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: [
        'identify-fraction',
        'read-fractions',
        'write-fractions',
        'read-write-fraction',
      ],
    },
    {
      number: 54,
      id: 'kntt-lesson-54',
      chapterId: 'kntt-chapter-10',
      title: 'Phân số và phép chia số tự nhiên',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['fraction-as-division'],
    },
    {
      number: 55,
      id: 'kntt-lesson-55',
      chapterId: 'kntt-chapter-10',
      title: 'Tính chất cơ bản của phân số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['fraction-basic-property', 'equivalent-fractions'],
    },
    {
      number: 56,
      id: 'kntt-lesson-56',
      chapterId: 'kntt-chapter-10',
      title: 'Rút gọn phân số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['reduce-fractions'],
    },
    {
      number: 57,
      id: 'kntt-lesson-57',
      chapterId: 'kntt-chapter-10',
      title: 'Quy đồng mẫu số các phân số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['common-denominator'],
    },
    {
      number: 58,
      id: 'kntt-lesson-58',
      chapterId: 'kntt-chapter-10',
      title: 'So sánh phân số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['compare-fractions'],
    },
    {
      number: 59,
      id: 'kntt-lesson-59',
      chapterId: 'kntt-chapter-10',
      title: 'Luyện tập chung',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'identify-fraction',
        'fraction-as-division',
        'fraction-basic-property',
        'reduce-fractions',
        'common-denominator',
        'compare-fractions',
      ],
    },
    {
      number: 60,
      id: 'kntt-lesson-60',
      chapterId: 'kntt-chapter-11',
      title: 'Phép cộng phân số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['add-fractions'],
    },
    {
      number: 61,
      id: 'kntt-lesson-61',
      chapterId: 'kntt-chapter-11',
      title: 'Phép trừ phân số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['subtract-fractions'],
    },
    {
      number: 62,
      id: 'kntt-lesson-62',
      chapterId: 'kntt-chapter-11',
      title: 'Luyện tập chung',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: ['add-fractions', 'subtract-fractions'],
    },
    {
      number: 63,
      id: 'kntt-lesson-63',
      chapterId: 'kntt-chapter-12',
      title: 'Phép nhân phân số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['multiply-fractions'],
    },
    {
      number: 64,
      id: 'kntt-lesson-64',
      chapterId: 'kntt-chapter-12',
      title: 'Phép chia phân số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['divide-fractions'],
    },
    {
      number: 65,
      id: 'kntt-lesson-65',
      chapterId: 'kntt-chapter-12',
      title: 'Tìm phân số của một số',
      semester: 2,
      kind: 'CORE',
      problemTypeIds: ['fraction-of-quantity'],
    },
    {
      number: 66,
      id: 'kntt-lesson-66',
      chapterId: 'kntt-chapter-12',
      title: 'Luyện tập chung',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: ['multiply-fractions', 'divide-fractions', 'fraction-of-quantity'],
    },
    {
      number: 67,
      id: 'kntt-lesson-67',
      chapterId: 'kntt-chapter-13',
      title: 'Ôn tập số tự nhiên',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'read-write-numbers',
        'write-natural-numbers',
        'place-and-class',
        'round-numbers',
        'compare-numbers',
        'natural-number-sequence',
      ],
    },
    {
      number: 68,
      id: 'kntt-lesson-68',
      chapterId: 'kntt-chapter-13',
      title: 'Ôn tập phép tính với số tự nhiên',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'column-addition',
        'column-subtraction',
        'multiply-one-digit',
        'multiply-two-digits',
        'divide-one-digit',
        'divide-two-digits',
        'operation-order',
        'addition-properties',
        'multiplication-properties',
      ],
    },
    {
      number: 69,
      id: 'kntt-lesson-69',
      chapterId: 'kntt-chapter-13',
      title: 'Ôn tập phân số',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'identify-fraction',
        'read-fractions',
        'write-fractions',
        'fraction-as-division',
        'fraction-basic-property',
        'reduce-fractions',
        'common-denominator',
        'compare-fractions',
      ],
    },
    {
      number: 70,
      id: 'kntt-lesson-70',
      chapterId: 'kntt-chapter-13',
      title: 'Ôn tập phép tính với phân số',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'add-fractions',
        'subtract-fractions',
        'multiply-fractions',
        'divide-fractions',
        'fraction-of-quantity',
      ],
    },
    {
      number: 71,
      id: 'kntt-lesson-71',
      chapterId: 'kntt-chapter-13',
      title: 'Ôn tập hình học và đo lường',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'measure-angle-degrees',
        'classify-angles',
        'perpendicular-lines',
        'parallel-perpendicular',
        'recognize-parallelogram-rhombus',
        'rectangle-perimeter',
        'rectangle-area',
        'square-perimeter',
        'square-area',
        'mass-conversion',
        'area-conversion',
        'time-conversion',
      ],
    },
    {
      number: 72,
      id: 'kntt-lesson-72',
      chapterId: 'kntt-chapter-13',
      title: 'Ôn tập một số yếu tố thống kê và xác suất',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'statistical-data-series',
        'read-data-table',
        'read-bar-chart',
        'compare-chart-data',
        'event-frequency',
      ],
    },
    {
      number: 73,
      id: 'kntt-lesson-73',
      chapterId: 'kntt-chapter-13',
      title: 'Ôn tập chung',
      semester: 2,
      kind: 'REVIEW',
      problemTypeIds: [
        'read-write-numbers',
        'column-addition',
        'multiply-one-digit',
        'identify-fraction',
        'rectangle-area',
        'statistical-data-series',
        'three-step-word-problem',
      ],
    },
  ],
};
